import { useSession } from 'next-auth/react';

import Head from 'next/head';
import Header from '@/components/Header';

export default function Home() {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <h1>BPS Stock Number Generator</h1>
        <p>{JSON.stringify(session)}</p>
        <p>{JSON.stringify(status)}</p>
      </main>
    </>
  );
}
